name: networks
channels:
  - anaconda
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorcet=3.0.0
  - cryptography=38.0.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2022.2.1
  - dask-core=2022.2.1
  - datashader=0.14.1
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.2.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2022.7.1
  - gdk-pixbuf=2.42.8
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - heapdict=1.0.1
  - holoviews=1.15.0
  - hvplot=0.8.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.3
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libffi=3.3
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm11=11.1.0
  - libllvm12=12.0.0
  - libpng=1.6.37
  - libpq=12.9
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libtool=2.4.6
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - notebook=6.4.12
  - nspr=4.33
  - nss=3.74
  - numba=0.56.3
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pandocfilters=1.5.0
  - panel=0.13.1
  - pango=1.50.7
  - param=1.12.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.4.8
  - pygments=2.11.2
  - pygraphviz=1.9
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.1
  - pyviz_comms=2.0.2
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scipy=1.9.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tbb=2021.6.0
  - tblib=1.7.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xarray=0.20.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.1.0
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - jinja2==3.0.1
    - openmatrix==0.3.5.0
    - pyqt5-sip==12.11.0
    - pyyaml==6.0
    - tables==3.7.0
prefix: /usr/local/anaconda3/envs/networks
